name: harry_likes_sally_example
description: Example project
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  patrol: ^3.6.1
  patrol_cli: ^3.4.0